/**
 * Turn loaded catalogs into a TypeScript declaration that types `t()`.
 *
 * Catalogs are JSON/YAML read at runtime, so the compiler cannot infer keys
 * from them — codegen is the only way to make `t('messages.greetingg')` a
 * compile error. The emitted file augments {@link TranslationKeys}, the same
 * declaration-merging idiom AdonisJS uses for `EventsList`.
 *
 * Not an AdonisJS API: `@adonisjs/i18n` types its own classes but leaves
 * translation keys as bare strings.
 */

import {
	extractMessageParams,
	type MessageParam,
} from "./formatters/IcuFormatter.js";
import type { Translations } from "./Rosetta.js";

export interface GenerateCatalogTypesOptions {
	/**
	 * The locale the keys are read from. Defaults to the first locale in
	 * `translations` — pass your `defaultLocale` to be explicit.
	 */
	referenceLocale?: string;
	/**
	 * The module specifier to augment. Defaults to `"@c9up/rosetta"`; override
	 * when re-exporting rosetta behind your own module.
	 */
	moduleName?: string;
}

/**
 * The TypeScript type a variable accepts, from how the message uses it.
 *
 * `select` widens to `(string & {})` on top of its branch keys: passing an
 * undeclared branch is legal ICU — it falls to `other` — so rejecting it would
 * be stricter than the runtime. The union is still there, for autocomplete.
 */
function paramType(param: MessageParam): string {
	switch (param.kind) {
		case "number":
		case "plural":
		case "selectordinal":
			return "number";
		case "date":
		case "time":
			return "DateTimeValue";
		case "select": {
			const branches = param.options ?? [];
			if (branches.length === 0) return "string";
			return `${branches.map(quote).join(" | ")} | (string & {})`;
		}
		default:
			// Plain `{name}` interpolation — stringified as-is.
			return "string | number";
	}
}

/** A TS string literal. Single-quoted to match the surrounding style. */
function quote(value: string): string {
	return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;
}

function renderParams(params: MessageParam[]): string {
	if (params.length === 0) {
		// No variables: `Record<string, never>` makes passing some an error,
		// rather than silently ignored.
		return "Record<string, never>";
	}
	// Keys come from catalog files and can hold anything, so quote every
	// property name rather than deciding which ones are identifiers.
	const fields = params
		.map((p) => `${quote(p.name)}: ${paramType(p)}`)
		.join("; ");
	return `{ ${fields} }`;
}

/**
 * Emit the `declare module` block typing every key of the reference locale.
 * Messages that do not parse are skipped and listed in a trailing comment —
 * codegen must not fail the build over one bad message; `checkCatalogs` is what
 * reports those.
 *
 * The result is a complete file: write it to e.g. `types/i18n.d.ts` and make
 * sure `tsconfig.json` includes it.
 */
export function generateCatalogTypes(
	translations: Translations,
	opts: GenerateCatalogTypesOptions = {},
): string {
	const locales = Object.keys(translations);
	const reference = opts.referenceLocale ?? locales[0];
	const moduleName = opts.moduleName ?? "@c9up/rosetta";
	const catalog = reference === undefined ? undefined : translations[reference];

	const lines: string[] = [
		"// Generated by @c9up/rosetta — do not edit.",
		`// Source locale: ${reference ?? "(none)"}`,
		"",
		"import type { DateTimeValue } from '@c9up/rosetta'",
		"",
		`declare module ${quote(moduleName)} {`,
		"\tinterface TranslationKeys {",
	];

	const skipped: string[] = [];
	if (catalog) {
		for (const key of Object.keys(catalog).sort()) {
			try {
				const params = extractMessageParams(catalog[key]);
				lines.push(`\t\t${quote(key)}: ${renderParams(params)}`);
			} catch {
				skipped.push(key);
			}
		}
	}

	lines.push("\t}", "}", "");
	if (skipped.length > 0) {
		lines.push(
			`// Skipped ${skipped.length} key(s) whose ICU syntax does not parse — run checkCatalogs:`,
			...skipped.map((k) => `//   ${k}`),
			"",
		);
	}
	return lines.join("\n");
}
