/**
 * Universal engine loader — auto-detects Node (NAPI) vs Browser (WASM).
 *
 * Node gets the stateful `RosettaEngine` class (resident catalog in Rust memory).
 * Browser gets the stateless WASM functions (re-parse catalog per call — acceptable
 * because browser apps typically have smaller catalogs than server-rendered i18n).
 */

export interface NativeRosettaEngine {
	loadCatalogs(catalogsJson: string): void;
	translate(
		key: string,
		paramsJson: string | undefined,
		chainJson: string,
		defaultValue: string | undefined,
	): string;
	has(key: string, chainJson: string): boolean;
}

interface NativeModule {
	RosettaEngine: new () => NativeRosettaEngine;
	translate: (
		catalogsJson: string,
		key: string,
		paramsJson: string | undefined,
		chainJson: string,
		defaultValue: string | undefined,
	) => string;
	has: (catalogsJson: string, key: string, chainJson: string) => boolean;
}

let native: NativeModule | undefined;
interface WasmStatelessApi {
	translate(
		catalogsJson: string,
		key: string,
		paramsJson: string | undefined,
		chainJson: string,
		defaultValue: string | undefined,
	): string;
	has(catalogsJson: string, key: string, chainJson: string): boolean;
}
let wasmModule: WasmStatelessApi | undefined;
let loadError: unknown;

const isNode =
	typeof globalThis.process !== "undefined" &&
	typeof globalThis.process.versions?.node === "string";

if (isNode) {
	try {
		const { createRequire } = await import("node:module");
		const { dirname, join } = await import("node:path");
		const { fileURLToPath } = await import("node:url");
		const { arch, platform } = await import("node:process");

		const nodeRequire = createRequire(import.meta.url);
		const currentDir = dirname(fileURLToPath(import.meta.url));

		const platformMap: Record<string, string> = {
			"linux-x64": "linux-x64-gnu",
			"linux-arm64": "linux-arm64-gnu",
			"darwin-x64": "darwin-x64",
			"darwin-arm64": "darwin-arm64",
			"win32-x64": "win32-x64-msvc",
		};

		const suffix = platformMap[`${platform}-${arch}`];
		if (suffix) {
			native = nodeRequire(join(currentDir, `../index.${suffix}.node`));
		}
	} catch (e) {
		loadError = e;
	}
} else {
	try {
		// The WASM glue generated by wasm-pack exports `translate` and `has` as
		// top-level functions with the exact same signatures as `WasmStatelessApi`.
		// We declare the import shape explicitly so no cast is needed.
		const wasm: { default: () => Promise<unknown> } & WasmStatelessApi =
			await import("../wasm/rosetta_engine_wasm.js");
		await wasm.default();
		wasmModule = wasm;
	} catch (e) {
		loadError = e;
	}
}

export function isNativeAvailable(): boolean {
	return native !== undefined || wasmModule !== undefined;
}

/** Create a stateful engine (Node NAPI only). Returns null in browser (WASM is stateless). */
export function createNativeEngine(): NativeRosettaEngine | null {
	if (!native) {
		if (!wasmModule) return null;
		const wasm = wasmModule;
		let catalogsJson = "{}";
		return {
			loadCatalogs(json: string) {
				catalogsJson = json;
			},
			translate(key, paramsJson, chainJson, defaultValue) {
				return wasm.translate(
					catalogsJson,
					key,
					paramsJson ?? undefined,
					chainJson,
					defaultValue ?? undefined,
				) as string;
			},
			has(key, chainJson) {
				return wasm.has(catalogsJson, key, chainJson) as boolean;
			},
		};
	}
	return new native.RosettaEngine();
}

// Legacy stateless exports (used by tests)
export function nativeTranslate(
	catalogsJson: string,
	key: string,
	paramsJson: string | undefined,
	chainJson: string,
	defaultValue: string | undefined,
): string {
	if (native)
		return native.translate(
			catalogsJson,
			key,
			paramsJson,
			chainJson,
			defaultValue,
		);
	if (wasmModule)
		return wasmModule.translate(
			catalogsJson,
			key,
			paramsJson,
			chainJson,
			defaultValue,
		) as string;
	throw new Error(
		`[ROSETTA_ENGINE_NOT_FOUND] ${loadError ?? "binary not found"}`,
		{ cause: loadError },
	);
}

export function nativeHas(
	catalogsJson: string,
	key: string,
	chainJson: string,
): boolean {
	if (native) return native.has(catalogsJson, key, chainJson);
	if (wasmModule)
		return wasmModule.has(catalogsJson, key, chainJson) as boolean;
	throw new Error(
		`[ROSETTA_ENGINE_NOT_FOUND] ${loadError ?? "binary not found"}`,
		{ cause: loadError },
	);
}
