/**
 * Optional Rust parser loader — NAPI under Node, WASM in the browser.
 *
 * The Rust side parses only: ICU message syntax and translation catalogs are
 * validated there and handed back as JSON for JavaScript to cache. Rendering
 * stays in JavaScript on ECMA-402, so CLDR plural rules and number/date
 * formatting track the runtime rather than a hand-maintained table.
 *
 * Every export here is best-effort. When no binary loads — an unlisted
 * platform, musl/Alpine, a browser without the wasm bundle — callers fall back
 * to the equivalent TypeScript parser and behaviour is unchanged.
 */

/**
 * Both parse entry points are optional: a binary built from an older revision
 * may not expose them, in which case the TypeScript parser takes over.
 */
interface NativeModule {
	parseMessage?: (message: string) => string;
	parseCatalog?: (input: string, format: string) => string;
}

interface WasmModule {
	parse_message?: (message: string) => string;
	parse_catalog?: (input: string, format: string) => string;
}

let native: NativeModule | undefined;
let wasmModule: WasmModule | undefined;
let loadError: unknown;

const isNode =
	typeof globalThis.process !== "undefined" &&
	typeof globalThis.process.versions?.node === "string";

if (isNode) {
	try {
		const { createRequire } = await import("node:module");
		const { dirname, join } = await import("node:path");
		const { fileURLToPath } = await import("node:url");
		const { arch, platform } = await import("node:process");

		const nodeRequire = createRequire(import.meta.url);
		const currentDir = dirname(fileURLToPath(import.meta.url));

		const platformMap: Record<string, string> = {
			"linux-x64": "linux-x64-gnu",
			"linux-arm64": "linux-arm64-gnu",
			"darwin-x64": "darwin-x64",
			"darwin-arm64": "darwin-arm64",
			"win32-x64": "win32-x64-msvc",
		};

		const suffix = platformMap[`${platform}-${arch}`];
		if (suffix) {
			native = nodeRequire(join(currentDir, `../index.${suffix}.node`));
		}
	} catch (e) {
		loadError = e;
	}
} else {
	try {
		// The WASM glue generated by wasm-pack exports `parse_message` and
		// `parse_catalog` as top-level functions with the exact same signatures
		// as `WasmModule`. We declare the import shape explicitly so no cast is
		// needed.
		const wasm: { default: () => Promise<unknown> } & WasmModule = await import(
			"../wasm/rosetta_engine_wasm.js"
		);
		await wasm.default();
		wasmModule = wasm;
	} catch (e) {
		loadError = e;
	}
}

export function isNativeAvailable(): boolean {
	return native !== undefined || wasmModule !== undefined;
}

/**
 * The error captured when neither the NAPI binary nor the WASM module could be
 * loaded, so callers can surface the REAL cause instead of a generic
 * "build the native engine" message that misleads browser/WASM users.
 */
export function getLoadError(): unknown {
	return loadError;
}

/** Parse ICU syntax in Rust when the current native/WASM build exposes it. */
export function nativeParseMessage(message: string): string | null {
	if (native?.parseMessage) return native.parseMessage(message);
	if (wasmModule?.parse_message) return wasmModule.parse_message(message);
	return null;
}

/** Parse a translation catalog in Rust when the native/WASM engine is loaded. */
export function nativeParseCatalog(
	input: string,
	format: "json" | "yaml" | "yml",
): string | null {
	if (native?.parseCatalog) return native.parseCatalog(input, format);
	if (wasmModule?.parse_catalog) return wasmModule.parse_catalog(input, format);
	return null;
}
