/**
 * Codegen for typed translation keys. The generated text is the contract, so
 * the assertions pin the emitted types; `tests/types/typed-keys.fixture.ts`
 * (run by `pnpm test:types`) proves the result actually constrains `t()`.
 */
import { describe, expect, it } from "vitest";
import { generateCatalogTypes } from "../../src/CatalogTypes.js";

describe("generateCatalogTypes", () => {
	it("maps each ICU use of a variable to the type it accepts", () => {
		const out = generateCatalogTypes(
			{
				en: {
					greeting: "Hello {name}",
					items: "{count, plural, one {# item} other {# items}}",
					rank: "{place, selectordinal, one {#st} other {#th}}",
					total: "{amount, number, ::currency/USD}",
					when: "{at, date, short}",
					clock: "{at, time, short}",
					gender: "{g, select, male {his} female {her} other {their}}",
					plain: "Nothing to interpolate",
				},
			},
			{ referenceLocale: "en" },
		);

		expect(out).toContain("'greeting': { 'name': string | number }");
		expect(out).toContain("'items': { 'count': number }");
		expect(out).toContain("'rank': { 'place': number }");
		expect(out).toContain("'total': { 'amount': number }");
		expect(out).toContain("'when': { 'at': DateTimeValue }");
		expect(out).toContain("'clock': { 'at': DateTimeValue }");
		expect(out).toContain("'plain': Record<string, never>");
		// A select keeps its branches for autocomplete but still accepts other
		// strings, because an undeclared branch legally falls through to `other`.
		expect(out).toContain(
			"'gender': { 'g': 'male' | 'female' | (string & {}) }",
		);
	});

	it("emits a compilable augmentation of the rosetta module", () => {
		const out = generateCatalogTypes({ en: { a: "A" } });
		expect(out).toContain("declare module '@c9up/rosetta' {");
		expect(out).toContain("interface TranslationKeys {");
		expect(out).toContain("import type { DateTimeValue } from '@c9up/rosetta'");
		expect(out).toContain("// Generated by @c9up/rosetta — do not edit.");
	});

	it("targets another module when rosetta is re-exported", () => {
		const out = generateCatalogTypes(
			{ en: { a: "A" } },
			{ moduleName: "#i18n" },
		);
		expect(out).toContain("declare module '#i18n' {");
	});

	it("keeps a multi-variable message's fields together", () => {
		const out = generateCatalogTypes({
			en: { mix: "{name} has {n, plural, one {# thing} other {# things}}" },
		});
		expect(out).toContain("'mix': { 'n': number; 'name': string | number }");
	});

	it("skips an unparsable message rather than failing the build", () => {
		const out = generateCatalogTypes({
			en: { good: "Fine", broken: "{count, plural, one {#}" },
		});
		expect(out).toContain("'good': Record<string, never>");
		expect(out).not.toContain("'broken':");
		expect(out).toContain("Skipped 1 key(s)");
		expect(out).toContain("//   broken");
	});

	it("escapes quotes in keys and variable names", () => {
		const out = generateCatalogTypes({ en: { "it's": "Hi {name}" } });
		expect(out).toContain("'it\\'s'");
	});

	it("handles no catalogs and an unknown reference locale", () => {
		expect(generateCatalogTypes({})).toContain("interface TranslationKeys {");
		expect(
			generateCatalogTypes({ en: { a: "A" } }, { referenceLocale: "de" }),
		).not.toContain("'a':");
	});

	it("sorts keys, so regenerating produces no diff churn", () => {
		const out = generateCatalogTypes({ en: { zebra: "Z", apple: "A" } });
		expect(out.indexOf("'apple'")).toBeLessThan(out.indexOf("'zebra'"));
	});
});
